# Generated by Django 5.0.13 on 2025-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_create_notifications_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
